// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Readline = require("readline");
var PervasivesU = require("rescript/lib/js/pervasivesU.js");

var rl = Readline.createInterface({
      input: Fs.createReadStream("sample.txt"),
      crlfDelay: PervasivesU.infinity
    });

rl.on("line", (function (line) {
        console.log("Received: " + line);
      }));

exports.rl = rl;
/* rl Not a pure module */
